version: "3.9"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./server:/server
    working_dir: /server
    command: npm start
    tty: true
    ports:
      - 3000:3000